#!/bin/sh

SHPOTIFY_CONFIG_DIR=~/.config/shpotify

env_dir=$SHPOTIFY_CONFIG_DIR/.env.d

if [ ! -e $env_dir ]; then
  >&2 echo "$env_dir/ doesn't exist!"
  exit 111
fi

if [ -z "$(ls -A $env_dir)" ]; then
  >&2 echo "$env_dir/ is empty!"
  exit 111
fi

for env_file in $env_dir/*; do
  key=$(basename $env_file)
  value=$(cat $env_file)
  export "$key=$value"
done

export SHPOTIFY_CONFIG_DIR
