#!/bin/sh

. ./load_env

refresh_token() {
  curl \
    --silent \
    -d "client_id=${SPOTIFY_CLIENT_ID}" \
    -d "client_secret=${SPOTIFY_CLIENT_SECRET}" \
    -d "grant_type=refresh_token" \
    -d "refresh_token=${SPOTIFY_REFRESH_TOKEN}" \
    https://accounts.spotify.com/api/token
}

refresh_response=$(refresh_token)
token=$(echo $refresh_response | jq -r '.access_token')

if [ "$token" = "null" ]; then
  echo "No token returned:"
  echo $refresh_response
  exit 111
else
  echo "New token:"
  echo $token | tee ./.env.d/SPOTIFY_ACCESS_TOKEN
fi
